-- +goose Up
BEGIN;

ALTER TABLE vade_mecum_codigos
    ALTER COLUMN idtipo TYPE VARCHAR,
    ALTER COLUMN tipo TYPE VARCHAR,
    ALTER COLUMN idcodigo TYPE VARCHAR,
    ALTER COLUMN nomecodigo TYPE VARCHAR,
    ALTER COLUMN "Cabecalho" TYPE VARCHAR,
    ALTER COLUMN "PARTE" TYPE VARCHAR,
    ALTER COLUMN idlivro TYPE VARCHAR,
    ALTER COLUMN livro TYPE VARCHAR,
    ALTER COLUMN livrotexto TYPE VARCHAR,
    ALTER COLUMN idtitulo TYPE VARCHAR,
    ALTER COLUMN titulo TYPE VARCHAR,
    ALTER COLUMN titulotexto TYPE VARCHAR,
    ALTER COLUMN idsubtitulo TYPE VARCHAR,
    ALTER COLUMN subtitulo TYPE VARCHAR,
    ALTER COLUMN subtitulotexto TYPE VARCHAR,
    ALTER COLUMN idcapitulo TYPE VARCHAR,
    ALTER COLUMN capitulo TYPE VARCHAR,
    ALTER COLUMN capitulotexto TYPE VARCHAR,
    ALTER COLUMN idsecao TYPE VARCHAR,
    ALTER COLUMN secao TYPE VARCHAR,
    ALTER COLUMN secaotexto TYPE VARCHAR,
    ALTER COLUMN idsubsecao TYPE VARCHAR,
    ALTER COLUMN subsecao TYPE VARCHAR,
    ALTER COLUMN subsecaotexto TYPE VARCHAR,
    ALTER COLUMN num_artigo TYPE VARCHAR,
    ALTER COLUMN "Normativo" TYPE VARCHAR,
    ALTER COLUMN "Ordem" TYPE VARCHAR;

COMMIT;

-- +goose Down
BEGIN;

ALTER TABLE vade_mecum_codigos
    ALTER COLUMN idtipo TYPE TEXT,
    ALTER COLUMN tipo TYPE TEXT,
    ALTER COLUMN idcodigo TYPE TEXT,
    ALTER COLUMN nomecodigo TYPE TEXT,
    ALTER COLUMN "Cabecalho" TYPE TEXT,
    ALTER COLUMN "PARTE" TYPE TEXT,
    ALTER COLUMN idlivro TYPE TEXT,
    ALTER COLUMN livro TYPE TEXT,
    ALTER COLUMN livrotexto TYPE TEXT,
    ALTER COLUMN idtitulo TYPE TEXT,
    ALTER COLUMN titulo TYPE TEXT,
    ALTER COLUMN titulotexto TYPE TEXT,
    ALTER COLUMN idsubtitulo TYPE TEXT,
    ALTER COLUMN subtitulo TYPE TEXT,
    ALTER COLUMN subtitulotexto TYPE TEXT,
    ALTER COLUMN idcapitulo TYPE TEXT,
    ALTER COLUMN capitulo TYPE TEXT,
    ALTER COLUMN capitulotexto TYPE TEXT,
    ALTER COLUMN idsecao TYPE TEXT,
    ALTER COLUMN secao TYPE TEXT,
    ALTER COLUMN secaotexto TYPE TEXT,
    ALTER COLUMN idsubsecao TYPE TEXT,
    ALTER COLUMN subsecao TYPE TEXT,
    ALTER COLUMN subsecaotexto TYPE TEXT,
    ALTER COLUMN num_artigo TYPE TEXT,
    ALTER COLUMN "Normativo" TYPE TEXT,
    ALTER COLUMN "Ordem" TYPE TEXT;

COMMIT;
